"""Apply a rough, eyeballed radial-distortion correction.

No checkerboard is available. We tried an automated plumb-line fit (straight
edges of the ruler/rod/mat gridlines - see git history of this file for that
approach) but the reference photos don't have enough curvature signal: the
cost landscape over k1 in [-0.8, 0.3] was nearly flat (~7% relative spread),
so the optimizer had no reliable minimum and just walked to whichever bound.
A visual sweep (dataset/calib/k1_sweep_round.jpg, k1 in {-0.5..0}) confirmed
the true geometric bowing is mild - much of the apparent "severe" distortion
in these photos is vignetting (dark corners) and the genuinely-round desk,
not lens warping of straight lines.

Given that, this uses a single moderate, visually-judged k1 (project owner
decision) rather than a fitted value. It is explicitly NOT a proper
calibration; revisit with a real checkerboard capture if downstream results
show it's insufficient.

Usage:
    python tools/estimate_distortion.py
Outputs:
    dataset/calib/camera_intrinsics.yaml
    dataset/calib/undistort_check_<name>.jpg   (before | after, side by side)
"""
import json
from pathlib import Path

import cv2
import numpy as np

REPO = Path(__file__).resolve().parent.parent
DATASET = REPO / "dataset"
CALIB_DIR = DATASET / "calib"
CALIB_DIR.mkdir(parents=True, exist_ok=True)

CHECK_IMAGES = ["ruler.jpg", "rod.jpg", "ruler_2.jpg", "round.jpg", "calib.jpg"]

# Eyeballed correction (project owner decision - see conversation): automated
# plumb-line fitting on available reference photos was inconclusive (flat cost
# landscape), so we use a single moderate barrel-correction coefficient.
K1 = -0.15
K2 = 0.0


def to_yaml(d, indent=0):
    lines = []
    pad = "  " * indent
    for k, v in d.items():
        if isinstance(v, dict):
            lines.append(f"{pad}{k}:")
            lines.append(to_yaml(v, indent + 1))
        elif isinstance(v, (list, str)):
            lines.append(f"{pad}{k}: {json.dumps(v)}")
        else:
            lines.append(f"{pad}{k}: {v}")
    return "\n".join(lines)


def main():
    ref = cv2.imread(str(DATASET / CHECK_IMAGES[0]))
    h, w = ref.shape[:2]
    cx, cy = w / 2.0, h / 2.0
    f = 0.9 * max(w, h)

    K = np.array([[f, 0, cx], [0, f, cy], [0, 0, 1]], dtype=np.float64)
    dist = np.array([K1, K2, 0, 0, 0], dtype=np.float64)

    out = {
        "image_width": int(w),
        "image_height": int(h),
        "camera_matrix": K.tolist(),
        "dist_coeffs": dist.tolist(),
        "note": (
            "NOT a proper calibration - no checkerboard available. Automated "
            "plumb-line fitting on the ruler/rod/mat-gridline edges gave a "
            "near-flat cost landscape (insufficient curvature signal), so "
            "k1/k2 here are a single moderate value chosen by visual "
            "comparison (see dataset/calib/k1_sweep_round.jpg). Revisit with "
            "a real checkerboard capture for a full recalibration."
        ),
    }
    (CALIB_DIR / "camera_intrinsics.yaml").write_text(
        "# Generated by tools/estimate_distortion.py (eyeballed, not fitted)\n"
        + to_yaml(out) + "\n"
    )
    print(f"wrote {CALIB_DIR / 'camera_intrinsics.yaml'} (k1={K1}, k2={K2})")

    new_K, _ = cv2.getOptimalNewCameraMatrix(K, dist, (w, h), 0.0, (w, h))
    for name in CHECK_IMAGES:
        path = DATASET / name
        if not path.exists():
            continue
        img = cv2.imread(str(path))
        und = cv2.undistort(img, K, dist, None, new_K)
        cv2.imwrite(str(CALIB_DIR / f"undistort_check_{name}"), np.hstack([img, und]))
    print(f"wrote before/after checks to {CALIB_DIR}")


if __name__ == "__main__":
    main()
